### PR TITLE
Add tip about creating timestamped migration files

### PR DESCRIPTION
**Pull request by karlhorky**
Add @lukeed's tip from #2 about creating timestamped migration files to the readme.

### CODE REVIEW

**Comment by mainanick** [comment]
@karlhorky any windows tip?

**Comment by karlhorky** [comment]
For Windows I generally suggest having a Bash command line for things like this. Either of the following should work well:

- Git Bash (is installed with [Git](https://git-scm.com/downloads))
- Windows Subsystem for Linux (aka WSL)

**Comment by lukeed** [comment]
Thanks :) Merging, but will be adding a `new` command that takes care of this.

**Comment by karlhorky** [comment]
Great, sounds good, thanks!

**Comment by lukeed** [comment]
Now available within v0.5.0 ::

```sh
# Sequential
$ ley new users  #=> migrations/00000-users.js
$ ley new teams  #=> migrations/00001-teams.js

# Timestamp
$ ley new users --timestamp #=> migrations/1584389617-users.js
$ ley new teams --timestamp #=> migrations/1584389631-teams.js

# Customize Filename / Extension
$ ley new users.ts #=> migrations/#####-users.ts
$ ley new create-teams #=> migrations/#####-create-teams.js
$ ley new "alter admin users" #=> migrations/#####-alter-admin-users.js

# Modify Prefix Length (non-timestamp only)
$ ley new users.ts --length 3 #=> migrations/###-users.ts
```

Works on Windows, too :)

**Pull request merged**
